
server:
  context-path: /auth-service
  port: 9081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: oauth
#      username:
#      password:
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
 level:
  org.springframework.security: DEBUG
  
security:
 oauth2: 
  resource:
   filter-order: 3
